### ISSUE TITLE
Empty directory not cloned

### ISSUE THREAD

**Issue by camhef** [billw2/rpi-clone#10]
I use an entry in /etc/fstab to map a local directory to a NAS.  I had created directory /mnt/nas on my SD card to map to my NAS.  rpi-clone did not create that directory on my new SD card image.

That may be by design (although I couldn't find reference) or an issue.

**Comment by SpoddyCoder** [comment]
Hi @camhef - this should now be resolved by the 1.6 release. Please download and install latest rpi-clone. If this resolves your issue, please click close, thanks :)

**Comment by camhef** [comment]
Just noticed the update - 4 years late.  Oops!  Issue closed.
