### ISSUE TITLE
How to find where mounted 

### ISSUE THREAD

**Issue by Glasairman** [billw2/rpi-clone#11]
1. my version does not show where the new SD is mounted, either by df -h or (proc/partitions, leaving me blindly trying sdx where x is anywhere between a and e without any system.

2 I think for consistency with other utilities  the parameter should be /dev/sdx and not sdx 

Otherwise great job

**Comment by crowzero** [comment]
Try 
```
sudo fdisk -l
```
to locate your SD-Card.

**Comment by SpoddyCoder** [comment]
@Glasairman it looks like @crowzero has helped you locate your card. For 2 - using /dev/sdN format was added to the 1.5 release.

Please download and install latest rpi-clone. If this resolves your issue, please click close, thanks :)
