### ISSUE TITLE
SDA partitions created then not found -> abort

### ISSUE THREAD

**Issue by Philtass** [billw2/rpi-clone#161]
I look at my save logs and I see that rpi-clone aborts with a message about sda1 and sda2 partitions not existing.
The proble seems to occur after partition resize. See file attached, please.
[rpi-clone verbose output.txt](https://github.com/billw2/rpi-clone/files/12478016/rpi-clone.verbose.output.txt)

**Comment by Philtass** [comment]
PS: last successfull save was 19th january 2023

**Comment by Philtass** [comment]
I did'nt check logs before today, shame on me !

**Comment by Philtass** [comment]
Thank's for fixing or tell me what to do for

**Comment by viniciuspaes** [comment]
Hi @Philtass, can you confirm that the devices exists with the command:
sudo fdisk -l

**Comment by Philtass** [comment]
Hi viniciuspaes !
sudo fdisk -l gives (at the end):
...
Disk /dev/sda: 29,8 GiB, 32010928128 bytes, 62521344 sectors
Disk model: Storage Device  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

**Comment by viniciuspaes** [comment]
Looking the log you have the OS installed in the SD card (/dev/mmcblk0)
Then /dev/mmcblk0p1 is the boot partition and /dev/mmcblk0p2 is the OS.

You want to clone everything to the SDA (assuming external drive). The RPI clone is not recognizing the label for SDA.

The command you used to clone was: 
sudo rpi-clone sda

Correct?

**Comment by Philtass** [comment]
Yes

**Comment by Philtass** [comment]
previously I used "sudo rpi-clone sda -U" with same result

**Comment by viniciuspaes** [comment]
It is weird that even parted is not recognizing SDA.

Double check if the command output the partitions:
cat /proc/partitions

**Comment by Philtass** [comment]
$ cat /proc/partitions
major minor  #blocks  name

   1        0       4096 ram0
   1        1       4096 ram1
   1        2       4096 ram2
   1        3       4096 ram3
   1        4       4096 ram4
   1        5       4096 ram5
   1        6       4096 ram6
   1        7       4096 ram7
   1        8       4096 ram8
   1        9       4096 ram9
   1       10       4096 ram10
   1       11       4096 ram11
   1       12       4096 ram12
   1       13       4096 ram13
   1       14       4096 ram14
   1       15       4096 ram15
 179        0    7815168 mmcblk0
 179        1     262144 mmcblk0p1
 179        2    7544832 mmcblk0p2
   8        0   31260672 sda

**Comment by viniciuspaes** [comment]
Just googled and saw some issues with parted. It is possible to create the label manually in case of corrupted or unrecognized disk label.

Have you tried to format the external disk manually already, to see the results?

**Comment by Philtass** [comment]
Not for the moment. I'm not sure of parameters.

**Comment by Philtass** [comment]
I see sda1 should be a fat32 and sda2 an ext3 but I never used command line to format a disk. I don't want to make a mess.

**Comment by Philtass** [comment]
Coul'd you give the right commands ?

**Comment by viniciuspaes** [comment]
Plug the external drive in your desktop computer. If using windows, try to format the drive and do some tests.

Then plug it again in the RPi and try the clone process. I did this way with my RPi 4 and worked in the first try.

Don't worry about creating the partitions, just check if the drive is working properly first.

**Comment by Philtass** [comment]
I use linux. Have you a command line to format..

**Comment by viniciuspaes** [comment]
Sure, hang on.

**Comment by Philtass** [comment]
Ok try that

**Comment by viniciuspaes** [comment]
To erase the external drive (double check if the external drive is mounted as /dev/sda)
sudo dd if=/dev/zero of=/dev/sda bs=16M

Using fdisk to create the partitions:
sudo fdisk /dev/sda


Don't worry with the filesystem yet, just try to run rpi-clone.

**Comment by Philtass** [comment]
ok done that:
Device     Boot  Start      End  Sectors  Size Id Type
/dev/sda1         2048   526335   524288  256M  c W95 FAT32 (LBA)
/dev/sda2       526336 62924799 62398464 29,8G 83 Linux

**Comment by viniciuspaes** [comment]
Nice, test the rpi-clone now.

**Comment by Philtass** [comment]
I run rpi-clone, it seems to work (it's long)

**Comment by Philtass** [comment]
bad news: 
sudo rpi-clone sda

Booted disk: mmcblk0 8.0GB                 Destination disk: sda 32.2GB
---------------------------------------------------------------------------
Part      Size    FS     Label           Part   Size    FS     Label
1 /boot   256.0M  fat32  --              1      256.0M  fat32  --
2 root      7.2G  ext4   rpidmtcz        2       29.8G  ext4   rpidmtcz
---------------------------------------------------------------------------
== SYNC mmcblk0 file systems to sda ==
/boot                 (47.5M used)   : SYNC to sda1 (256.0M size)
/                     (1.8G used)    : SYNC to sda2 (29.8G size)
---------------------------------------------------------------------------
Run setup script       : no.
Verbose mode           : no.
-----------------------:

Ok to proceed with the clone?  (yes/no): y

Syncing file systems (can take a long time)
Syncing mounted partitions:
  Mounting /dev/sda2 on /mnt/clone
  => rsync // /mnt/clone with-root-excludes ...rsync: recv_generator: mkdir "/mnt/clone/var" failed: Bad message (74)
*** Skipping any contents from this failed directory ***
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1207) [sender=3.1.3]

mkdir: impossible de créer le répertoire « /mnt/clone/boot »: Message invalide
  Mounting /dev/sda1 on /mnt/clone/boot
mount: /mnt/clone/boot: cannot mount; probably corrupted filesystem on /dev/sda1.
    Mount failure of /dev/sda1 on /mnt/clone/boot.
  unmounting /mnt/clone
Aborting!

**Comment by Philtass** [comment]
sorry for weird formated text

**Comment by viniciuspaes** [comment]
The SD card you are trying to clone, what OS do you have installed?

It is possible to manually create the boot partition, and then you just rsync the second partition (sda2).

**Comment by Philtass** [comment]
It's a standard raspbian, for a domoticz server.

**Comment by Philtass** [comment]
on a RPI 3B

**Comment by framps** [comment]
> I did'nt check logs before today, shame on me !

Why don't you create a small wrapper script which calls rpi-clone and sends a failure eMail to you if rpi-clone fails :wink:

**Comment by Philtass** [comment]
Hi framps. Good idea !

**Comment by Philtass** [comment]
But first I'd like to fix rpi-clone. Any Idea ?

**Comment by viniciuspaes** [comment]
Do you have another external drive available? So we can isolate the problem.

**Comment by Philtass** [comment]
I try with another SD card with only one partition. rpi-clone creates the 2 partitions and continues... for the moment

**Comment by Philtass** [comment]
done successfully ! The problem came from the SD card I guess

**Comment by Philtass** [comment]
Thanks for help and advices !
