### ISSUE TITLE
Suggest remove redirection of mkfs statement

### ISSUE THREAD

**Issue by pensionado** [billw2/rpi-clone#21]
Due to the >/dev/null on the MKFS statement I waited for a day, because I didn't see it (tried) to prompt me for proceed or not (because of existing DOS partition).  After removed it was done in minutes.

**Comment by AWSBarker** [comment]
Agreed, I had same issue - waiting a night with the above hidden prompt 'found dos partition'.

I hit 'y' twice to clear it to run.

Thanks pensionado otherwise I would have still been waiting...!
AWSB

**Comment by SpoddyCoder** [comment]
Hi @pensionado @AWSBarker - thanks for the feedback, this was resolved in the 1.3 release. Please download and install latest rpi-clone. If this resolves your issue, please click close, thanks :)
