### ISSUE TITLE
Does the script work with newer versions of Raspbian?

### ISSUE THREAD

**Issue by bosschaert** [billw2/rpi-clone#3]
The following article http://learn.adafruit.com/adafruit-raspberry-pi-lesson-1-preparing-and-sd-card-for-your-raspberry-pi/make-a-backup-image has a warning message listed with the script: 

```
Note: This script only works with occidentalis 0.2 and older versions of Raspbian
```

Does the script need to be updated to support newer versions?

**Comment by SpoddyCoder** [comment]
@bosschaert that is a very old post. I can confirm that latest version of rpi-clone works perfectly with latest release of Raspbian - currently "Jessie". Please download and install latest rpi-clone. If this resolves your issue, please click close, thanks :)

**Comment by bosschaert** [comment]
@SpoddyCoder thanks for confirming! Closing the issue as the latest works perfectly for me.
