### ISSUE TITLE
No -b option to findmnt on wheeze raspbian

### ISSUE THREAD

**Issue by 6b6561** [billw2/rpi-clone#47]
rpi-clone fails on wheeze because there is no -b option available on the findmnt command. This is with rpi-clone version 2.0.6

`root@xxx:/ss/rpi-clone# **rpi-clone sda**
findmnt: invalid option -- 'b'

Usage:
 findmnt [options]
 findmnt [options] <device> | <mountpoint>
 findmnt [options] <device> <mountpoint>
 findmnt [options] [--source <device>] [--target <mountpoint>]

Options:
 -s, --fstab            search in static table of filesystems
 -m, --mtab             search in table of mounted filesystems
 -k, --kernel           search in kernel table of mounted
                          filesystems (default)

 -p, --poll[=<list>]    monitor changes in table of mounted filesystems
 -w, --timeout <num>    upper limit in milliseconds that --poll will block

 -a, --ascii            use ASCII chars for tree formatting
 -c, --canonicalize     canonicalize printed paths
`

**Comment by billw2** [comment]
The -b option is removed.
Thanks,

**Comment by 6b6561** [comment]
Confirmed to work! A big thank you!
